name: TSS-Maj
version: 0.0.11-BETA
main: com.majere.tss.Core
authors: [Majere]
description: Primary plugin for the Tekkit Space Suite!

commands:
  staffchattoggle:
    description: Command to toggle staff chat!
    aliases: [sct]
  staffchat:
    description: Command used to chat it staff chat!
    aliases: [sc]
  kick:
    description: Command used to kick a player!
  fakeleave:
    description: Command used to fake leave the server!
    aliases: [fl]